"""Add broker_user_id to BrokerInfo table

Revision ID: c3427cb92c26
Revises: 4cf9bb4dc061
Create Date: 2024-11-12 17:06:58.698234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3427cb92c26'
down_revision = '4cf9bb4dc061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broker_user_id', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_info', schema=None) as batch_op:
        batch_op.drop_column('broker_user_id')

    # ### end Alembic commands ###
