"""Add broker_user_id to BrokerInfo table

Revision ID: feba5f0029f7
Revises: c3427cb92c26
Create Date: 2024-11-14 17:58:30.118263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feba5f0029f7'
down_revision = 'c3427cb92c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ath', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('how_far', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('highest_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_shares', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sl_point', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ten_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('twenty_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('thirty_percent', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('investment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sl', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ready_to_lose', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nsesymboltoken', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tp1', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tp2', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tp3', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('trailing_sl', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fifty_two_w_high', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('which_strategy', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('trade_status', sa.String(length=50), nullable=False))
        batch_op.drop_column('quantity')
        batch_op.drop_column('sell_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('trade_status')
        batch_op.drop_column('which_strategy')
        batch_op.drop_column('fifty_two_w_high')
        batch_op.drop_column('trailing_sl')
        batch_op.drop_column('tp3')
        batch_op.drop_column('tp2')
        batch_op.drop_column('tp1')
        batch_op.drop_column('nsesymboltoken')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('ready_to_lose')
        batch_op.drop_column('sl')
        batch_op.drop_column('investment')
        batch_op.drop_column('thirty_percent')
        batch_op.drop_column('twenty_percent')
        batch_op.drop_column('ten_percent')
        batch_op.drop_column('sl_point')
        batch_op.drop_column('total_shares')
        batch_op.drop_column('highest_price')
        batch_op.drop_column('how_far')
        batch_op.drop_column('ath')

    # ### end Alembic commands ###
